CREATE TABLE persons (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	rut INT NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	birthday DATE NULL,
	active BOOL NULL,
	CONSTRAINT persons_pk PRIMARY KEY (id),
	CONSTRAINT persons_un UNIQUE (rut)
);